stages:
  - install
  - build
  - test
  - security
  - deploy
  - integration

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"


########################################################
# CONFIG
########################################################

variables:
  # Laravel .env file
  FEATURE_BACKEND: "true"
  FEATURE_BACKEND_RESET: "true"
  FEATURE_APP_ACCOUNTS: "true"
  FEATURE_SHOP: "false"
  FEATURE_MULTI_LANG: "true"

# files that trigger php build and tests
.php-changes: &php-changes
  changes:
    - "app/**/*"
    - "config/**/*"
    - "database/**/*"
    - "routes/**/*"
    - "resources/views/**/*"
    - "tests/PHPUnit/**/*"
    - "composer.json"
    - "composer.lock"

# files that trigger javascript build and tests
.javascript-changes: &javascript-changes
  changes:
    - "resources/js/**/*"
    - "resources/lang/**/*"
    - "resources/sass/**/*"
    - "resources/svg/**/*"
    - "tests/Vitest/**/*"
    - "tsconfig.json"
    - "vite.config.js"


########################################################
# INSTALL
########################################################

env:
  stage: install
  image: alpine:3.20.2
  before_script:
    - apk add bash
  script:
    - ./scripts/ci-cd/gitlab/install_env.sh
  artifacts:
    expire_in: 1 day
    paths:
      - .env
      - .env.testing


node_modules:
  stage: install
  image: oven/bun:1.2.4-alpine
  needs:
    - env
  before_script:
    - apk add bash
  script:
    - ./scripts/ci-cd/gitlab/install_node_modules.sh
  rules:
    - changes:
      - "package.json"
      - "package-lock.json"
      - "bun.lock"
  cache:
    key: node-modules
    paths:
      - package.json
      - package-lock.json
      - bun.lock
      - node_modules/
    policy: push


########################################################
# BUILD
########################################################

composer:
  stage: build
  image: lorisleiva/laravel-docker:8.2
  script:
    - ./scripts/ci-cd/gitlab/install_composer.sh
  rules:
    - changes:
        - "composer.json"
        - "composer.lock"
  cache:
    key: composer
    paths:
      - composer.json
      - composer.lock
      - vendor/
    policy: push
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/


bun:
  stage: build
  image: oven/bun:1.2.4-alpine
  before_script:
    # bugfix: npm ignores optional dependencies
    - bun install @rollup/rollup-linux-x64-musl || true
    - bun install @rollup/rollup-linux-arm64-musl || true
  script:
    - bun run svg
    - bun run production
  rules:
    - <<: *javascript-changes
  cache:
    - key: node-modules
      paths:
        - package.json
        - package-lock.json
        - bun.lock
        - node_modules/
      policy: pull
    - key: public-build
      paths:
        - public/build/
        - public/svg/
      policy: push
  artifacts:
    expire_in: 1 day
    paths:
      - public/build/
      - public/svg/


########################################################
# TEST
########################################################

phpunit:
  stage: test
  image: lorisleiva/laravel-docker:8.2
  dependencies:
    - env
  before_script:
    - php artisan migrate:fresh --env=testing
    # replace localhost storage requests with absolute file path
    - sed -i 's,env("APP_URL")."storage/testing/",storage_path("app/public/testing"),' config/filesystems.php
  script:
    - XDEBUG_MODE=coverage php artisan test --parallel --processes=4 --configuration=./tests/PHPUnit/phpunit.xml --coverage-cobertura=./tests/PHPUnit/CodeCoverage/coverage-cobertura.xml
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      <<: *php-changes
    - if: $CI_COMMIT_BRANCH == "develop"
      allow_failure: true
  #coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  cache:
    - key: composer
      paths:
        - composer.json
        - composer.lock
        - vendor/
      policy: pull
    - key: public-build
      paths:
        - public/build/
        - public/svg/
      policy: pull

  # artifacts:
  #   when: always
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: tests/PHPUnit/CodeCoverage/cobertura-coverage.xml


vitest:
  stage: test
  image: node:20-alpine3.20
  needs:
    - job: node_modules
      optional: true
    - job: env
  before_script:
    # set timezone to "Europe/Berlin"
    - apk add --no-cache tzdata
    - cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    # bugfix: npm ignores optional dependencies
    - npm install @rollup/rollup-linux-x64-musl || true
    - npm install @rollup/rollup-linux-arm64-musl || true
  script:
    - LARAVEL_BYPASS_ENV_CHECK=1 npm run vitest --coverage.reporter=cobertura
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      <<: *javascript-changes
    - if: $CI_COMMIT_BRANCH == "develop"
      allow_failure: true
  coverage: '/All files(?:[^|]*\|){4}\s*(\S+)/'
  cache:
    key: node-modules
    paths:
      - package.json
      - package-lock.json
      - bun.lock
      - node_modules/
    policy: pull
    # reports:
    #   coverage_report:
    #     coverage_format: cobertura
    #     path: tests/Vitest/CodeCoverage/cobertura-coverage.xml


phpcs:
  stage: test
  image: lorisleiva/laravel-docker:8.2
  needs:
    - env
  before_script:
    - rm composer.lock
    - rm composer.json
    - composer require --dev "squizlabs/php_codesniffer=*"
  script:
    - ./vendor/bin/phpcs --standard=./tests/PHPCS/ruleset.xml app
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      <<: *php-changes
    - if: $CI_COMMIT_BRANCH == "develop"
      allow_failure: true


########################################################
# SECURITY
########################################################

semgrep:
  stage: security
  image: semgrep/semgrep
  dependencies: []
  needs:
    - env
  script: semgrep ci
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    <<: *php-changes
  # allow triggering a scan manually from the gitlab UI
  - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN


########################################################
# DEPLOY
########################################################

.install_ssh: &install_ssh
  # install and run ssh agent
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  # add private key
  - chmod 400 "$PRIVATE_KEY"
  - ssh-add "$PRIVATE_KEY"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # create ssh config
  - echo "Host target" > ~/.ssh/config
  - echo "  HostName $SERVER_DOMAIN" >> ~/.ssh/config
  - echo "  Port $SERVER_PORT" >> ~/.ssh/config
  - echo "  User $SERVER_USER" >> ~/.ssh/config
  - echo "  IdentityFile $PRIVATE_KEY" >> ~/.ssh/config
  - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  # remove trailing slash from $SERVER_PATH
  - SERVER_PATH=$(echo $SERVER_PATH | sed 's:/*$::')
  # enable private key on target
  - scp $PRIVATE_KEY target:~/.ssh/gitlab_ci
  - ssh target "chmod 600 ~/.ssh/gitlab_ci"
  - ssh target "cd $SERVER_PATH && git config core.sshCommand 'ssh -i ~/.ssh/gitlab_ci'"


.update_repository: &update_repository
  - if [ -d "vendor" ]; then rsync -rz --delete vendor/ target:$SERVER_PATH/vendor/; fi
  # update code
  - ssh target "cd $SERVER_PATH && git reset --hard && git pull"
  # upload build artifacts
  - if [ -d "public/build" ]; then rsync -r --delete public/build/ target:$SERVER_PATH/public/build/; fi
  - if [ -d "public/svg" ]; then rsync -r --delete public/svg/ target:$SERVER_PATH/public/svg/; fi
  # update laravel
  - ssh target "cd $SERVER_PATH && ./scripts/ci-cd/gitlab/update_deployment.sh"
  # disable private key on target
  - ssh target "rm ~/.ssh/gitlab_ci"
  - ssh target "cd $SERVER_PATH && git config --unset core.sshCommand"


.deploy-job: &deploy-job
  stage: deploy
  image: lorisleiva/laravel-docker:8.2
  #tags: [deploy]
  script:
    - *install_ssh
    - *update_repository


develop:
  <<: *deploy-job
  resource_group: develop
  environment:
    name: develop
    url: $SERVER_URL
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"


staging:
  <<: *deploy-job
  resource_group: staging
  environment:
    name: staging
    url: $SERVER_URL
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


production:
  <<: *deploy-job
  resource_group: production
  environment:
    name: production
    url: $SERVER_URL
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual


########################################################
# INTEGRATION TEST
########################################################

.hurl-job: &hurl-job
  stage: integration
  image: alpine:3.20.2
  script:
    - apk add bash
    - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing hurl
    - echo "verifying deployment on $SERVER_DOMAIN:$SERVER_PATH"
    - ./scripts/ci-cd/gitlab/hurl_tests.sh $SERVER_URL


hurl-develop:
  <<: *hurl-job
  environment:
    name: develop
    url: $SERVER_URL
  rules:
      - if: $CI_COMMIT_BRANCH == "develop"
        <<: *php-changes
        <<: *javascript-changes
  needs:
    - env
    - develop


hurl-staging:
  <<: *hurl-job
  environment:
    name: staging
    url: $SERVER_URL
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        <<: *php-changes
        <<: *javascript-changes
  needs:
    - env
    - staging


hurl-production:
  <<: *hurl-job
  environment:
    name: production
    url: $SERVER_URL
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        <<: *php-changes
        <<: *javascript-changes
  needs:
    - env
    - production
